name: Create release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: remla23-team5/cicd/.github/workflows/release.yaml@test
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: update version
        run: |
          mvn -q versions:set -DnewVersion="${{ needs.release.outputs.version }}"
          echo "$(cat pom.xml)"
      - name: Publish package
        run: mvn --batch-mode -Drevision=${{ github.event.release.tag_name }} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}