name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    uses: remla23-team5/cicd/.github/workflows/release.yaml@main
  publish:
    name: Publish to Github package registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Update version
        run: |
          mvn -q versions:set -DnewVersion="${{ needs.release.outputs.version }}"

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}