name: Tag & Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create new release
    uses: remla23-team5/cicd/.github/workflows/release.yaml@update-release-snapshot
    secrets: inherit
  publish-maven:
    name: Publish maven package
    needs: create-release
    uses: remla23-team5/cicd/.github/workflows/publish-maven.yaml@update-release-snapshot
    with:
      version: ${{ needs.create-release.outputs.version }}